[project]
name = "cardano_governance"
version = "0.1.0"
description = "cardano-governance using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.13"
dependencies = [
    "crewai[tools]>=0.108.0,<1.0.0",
    "vadersentiment (>=3.3.2,<4.0.0)"
]

[project.scripts]
cardano_governance = "cardano_governance.main:run"
run_crew = "cardano_governance.main:run"
train = "cardano_governance.main:train"
replay = "cardano_governance.main:replay"
test = "cardano_governance.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
